/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<'index', '/', Record<never, never>, Record<never, never>>,
    'sign-in': RouteRecordInfo<'sign-in', '/auth/sign-in', Record<never, never>, Record<never, never>>,
    'sign-up': RouteRecordInfo<'sign-up', '/auth/sign-up', Record<never, never>, Record<never, never>>,
    'backstage.index': RouteRecordInfo<'backstage.index', '/backstage', Record<never, never>, Record<never, never>>,
    'backstage.ledgers': RouteRecordInfo<'backstage.ledgers', '/backstage/ledger', Record<never, never>, Record<never, never>>,
    'backstage.posts': RouteRecordInfo<'backstage.posts', '/backstage/posts', Record<never, never>, Record<never, never>>,
    'backstage.tracks': RouteRecordInfo<'backstage.tracks', '/backstage/track', Record<never, never>, Record<never, never>>,
    'backstage.users': RouteRecordInfo<'backstage.users', '/backstage/users', Record<never, never>, Record<never, never>>,
  }
}
